# Generated by Django 4.0.3 on 2022-04-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('price', models.FloatField()),
                ('weight', models.IntegerField()),
                ('count', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
