# Generated by Django 4.0.3 on 2022-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='description',
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='link',
            field=models.CharField(max_length=1024),
        ),
    ]
