# Generated by Django 4.0.3 on 2022-04-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_itemrequest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
